repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.4.20
    hooks:
      - id: uv-export
        args: ['--no-hashes']
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.4.20
    hooks:
      # Update the uv lockfile
      - id: uv-lock
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.6.9
    hooks:
      # Run the linter.
      - id: ruff
        args: [--fix]
      # Run the formatter.
      - id: ruff-format
